import { create } from 'zustand'

export type Language = 'en' | 'es' | 'fr' | 'it' | 'de' | 'ja' | 'zh' | 'pt' | 'hi' | 'kn' | 'ta' | 'bn' | 'mr' | 'ml' | 'te' | 'or' | 'as' | 'pa' | 'gu'

type LanguageState = {
  lang: Language
  setLang: (l: Language) => void
}

const LANG_KEY = 'admin_language'

const validLanguages = ['en', 'es', 'fr', 'it', 'de', 'ja', 'zh', 'pt', 'hi', 'kn', 'ta', 'bn', 'mr', 'ml', 'te', 'or', 'as', 'pa', 'gu']

function readLang(): Language {
  const saved = localStorage.getItem(LANG_KEY) as Language | null
  if (saved && validLanguages.includes(saved)) {
    return saved
  }
  return 'en'
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  lang: readLang(),
  setLang: (l) => {
    localStorage.setItem(LANG_KEY, l)
    set({ lang: l })
  }
}))

// Translation mappings
export const translations: Record<Language, Record<string, string>> = {
  en: {
    'dashboard': 'Dashboard',
    'properties': 'Properties',
    'agents': 'Agents',
    'customers': 'Customers',
    'transactions': 'Transactions',
    'support': 'Support',
    'analytics': 'Analytics',
    'orders': 'Orders',
    'inbox': 'Inbox',
    'calendar': 'Calendar',
    'users': 'Users',
    'settings': 'Settings',
    'add': 'Add',
    'search': 'Search',
    'filter': 'Filter',
    'edit': 'Edit',
    'delete': 'Delete',
    'view': 'View',
    'save': 'Save',
    'cancel': 'Cancel',
    'logout': 'Logout'
  },
  es: {
    'dashboard': 'Panel',
    'properties': 'Propiedades',
    'agents': 'Agentes',
    'customers': 'Clientes',
    'transactions': 'Transacciones',
    'support': 'Soporte',
    'analytics': 'Analítica',
    'orders': 'Pedidos',
    'inbox': 'Bandeja de entrada',
    'calendar': 'Calendario',
    'users': 'Usuarios',
    'settings': 'Configuración',
    'add': 'Agregar',
    'search': 'Buscar',
    'filter': 'Filtro',
    'edit': 'Editar',
    'delete': 'Eliminar',
    'view': 'Ver',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'logout': 'Cerrar sesión'
  },
  fr: {
    'dashboard': 'Tableau de bord',
    'properties': 'Propriétés',
    'agents': 'Agents',
    'customers': 'Clients',
    'transactions': 'Transactions',
    'support': 'Support',
    'analytics': 'Analyses',
    'orders': 'Commandes',
    'inbox': 'Boîte de réception',
    'calendar': 'Calendrier',
    'users': 'Utilisateurs',
    'settings': 'Paramètres',
    'add': 'Ajouter',
    'search': 'Rechercher',
    'filter': 'Filtrer',
    'edit': 'Éditer',
    'delete': 'Supprimer',
    'view': 'Voir',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'logout': 'Déconnexion'
  },
  it: {
    'dashboard': 'Cruscotto',
    'properties': 'Proprietà',
    'agents': 'Agenti',
    'customers': 'Clienti',
    'transactions': 'Transazioni',
    'support': 'Supporto',
    'analytics': 'Analisi',
    'orders': 'Ordini',
    'inbox': 'Posta in arrivo',
    'calendar': 'Calendario',
    'users': 'Utenti',
    'settings': 'Impostazioni',
    'add': 'Aggiungi',
    'search': 'Cerca',
    'filter': 'Filtro',
    'edit': 'Modifica',
    'delete': 'Elimina',
    'view': 'Visualizza',
    'save': 'Salva',
    'cancel': 'Annulla',
    'logout': 'Disconnetti'
  },
  de: {
    'dashboard': 'Instrumententafel',
    'properties': 'Eigenschaften',
    'agents': 'Agenten',
    'customers': 'Kunden',
    'transactions': 'Transaktionen',
    'support': 'Support',
    'analytics': 'Analytik',
    'orders': 'Bestellungen',
    'inbox': 'Posteingang',
    'calendar': 'Kalender',
    'users': 'Benutzer',
    'settings': 'Einstellungen',
    'add': 'Hinzufügen',
    'search': 'Suchen',
    'filter': 'Filter',
    'edit': 'Bearbeiten',
    'delete': 'Löschen',
    'view': 'Ansicht',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'logout': 'Abmelden'
  },
  ja: {
    'dashboard': 'ダッシュボード',
    'properties': 'プロパティ',
    'agents': 'エージェント',
    'customers': '顧客',
    'transactions': '取引',
    'support': 'サポート',
    'analytics': '分析',
    'orders': '注文',
    'inbox': '受信トレイ',
    'calendar': 'カレンダー',
    'users': 'ユーザー',
    'settings': '設定',
    'add': '追加',
    'search': '検索',
    'filter': 'フィルター',
    'edit': '編集',
    'delete': '削除',
    'view': '表示',
    'save': '保存',
    'cancel': 'キャンセル',
    'logout': 'ログアウト'
  },
  zh: {
    'dashboard': '仪表板',
    'properties': '属性',
    'agents': '代理',
    'customers': '客户',
    'transactions': '交易',
    'support': '支持',
    'analytics': '分析',
    'orders': '订单',
    'inbox': '收件箱',
    'calendar': '日历',
    'users': '用户',
    'settings': '设置',
    'add': '添加',
    'search': '搜索',
    'filter': '筛选',
    'edit': '编辑',
    'delete': '删除',
    'view': '查看',
    'save': '保存',
    'cancel': '取消',
    'logout': '登出'
  },
  pt: {
    'dashboard': 'Painel',
    'properties': 'Propriedades',
    'agents': 'Agentes',
    'customers': 'Clientes',
    'transactions': 'Transações',
    'support': 'Suporte',
    'analytics': 'Análise',
    'orders': 'Pedidos',
    'inbox': 'Caixa de entrada',
    'calendar': 'Calendário',
    'users': 'Usuários',
    'settings': 'Configurações',
    'add': 'Adicionar',
    'search': 'Pesquisar',
    'filter': 'Filtro',
    'edit': 'Editar',
    'delete': 'Excluir',
    'view': 'Visualizar',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'logout': 'Sair'
  },
  hi: {
    'dashboard': 'डैशबोर्ड',
    'properties': 'संपत्ति',
    'agents': 'एजेंट',
    'customers': 'ग्राहक',
    'transactions': 'लेनदेन',
    'support': 'सहायता',
    'analytics': 'विश्लेषण',
    'orders': 'ऑर्डर',
    'inbox': 'इनबॉक्स',
    'calendar': 'कैलेंडर',
    'users': 'उपयोगकर्ता',
    'settings': 'सेटिंग्स',
    'add': 'जोड़ें',
    'search': 'खोजें',
    'filter': 'फ़िल्टर',
    'edit': 'संपादित करें',
    'delete': 'हटाएं',
    'view': 'देखें',
    'save': 'सेव करें',
    'cancel': 'रद्द करें',
    'logout': 'लॉग आउट'
  },
  kn: {
    'dashboard': 'ಡ್ಯಾಷ್ಬೋರ್ಡ್',
    'properties': 'ಆಸ್ತಿಗಳು',
    'agents': 'ಏಜೆಂಟರು',
    'customers': 'ಗ್ರಾಹಕರು',
    'transactions': 'ವಹಿವಾಟುಗಳು',
    'support': 'ಬೆಂಬಲ',
    'analytics': 'ವಿಶ್ಲೇಷಣೆ',
    'orders': 'ಆದೇಶಗಳು',
    'inbox': 'ಇನ್ಬಾಕ್ಸ್',
    'calendar': 'ಕ್ಯಾಲೆಂಡರ್',
    'users': 'ಬಳಕೆದಾರರು',
    'settings': 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
    'add': 'ಸೇರಿಸಿ',
    'search': 'ಹುಡುಕಿ',
    'filter': 'ಫಿಲ್ಟರ್',
    'edit': 'ಸಂಪಾದಿಸಿ',
    'delete': 'ಅಳಿಸಿ',
    'view': 'ನೋಡಿ',
    'save': 'ಉಳಿಸಿ',
    'cancel': 'ರದ್ದು',
    'logout': 'ಲಾಗ್ ಔಟ್'
  },
  ta: {
    'dashboard': 'டாஷ்போர்டு',
    'properties': 'பண்புகள்',
    'agents': 'முகவர்கள்',
    'customers': 'வாடிக்கையாளர்கள்',
    'transactions': 'பரிவர்த்தனைகள்',
    'support': 'ஆதரவு',
    'analytics': 'பகுப்பாய்வு',
    'orders': 'ஆர்டர்கள்',
    'inbox': 'இன்பாக்ஸ்',
    'calendar': 'காலெண்டர்',
    'users': 'பயனர்கள்',
    'settings': 'அமைப்புகள்',
    'add': 'சேர்',
    'search': 'தேடு',
    'filter': 'வடிகட்டி',
    'edit': 'திருத்து',
    'delete': 'அழி',
    'view': 'காட்டு',
    'save': 'சேமி',
    'cancel': 'ரத்து',
    'logout': 'வெளியேறு'
  },
  bn: {
    'dashboard': 'ড্যাশবোর্ড',
    'properties': 'সম্পত্তি',
    'agents': 'এজেন্ট',
    'customers': 'গ্রাহক',
    'transactions': 'লেনদেন',
    'support': 'সমর্থন',
    'analytics': 'বিশ্লেষণ',
    'orders': 'অর্ডার',
    'inbox': 'ইনবক্স',
    'calendar': 'ক্যালেন্ডার',
    'users': 'ব্যবহারকারী',
    'settings': 'সেটিংস',
    'add': 'যোগ করুন',
    'search': 'অনুসন্ধান',
    'filter': 'ফিল্টার',
    'edit': 'সম্পাদনা',
    'delete': 'মুছুন',
    'view': 'দেখুন',
    'save': 'সংরক্ষণ',
    'cancel': 'বাতিল',
    'logout': 'লগ আউট'
  },
  mr: {
    'dashboard': 'डॅशबोर्ड',
    'properties': 'मालमत्ता',
    'agents': 'एजंट',
    'customers': 'ग्राहक',
    'transactions': 'व्यवहार',
    'support': 'आधार',
    'analytics': 'विश्लेषण',
    'orders': 'ऑर्डर',
    'inbox': 'इनबॉक्स',
    'calendar': 'कॅलेंडर',
    'users': 'वापरकर्ते',
    'settings': 'सेटिंग्ज',
    'add': 'जोडा',
    'search': 'शोधा',
    'filter': 'फिल्टर',
    'edit': 'संपादित करा',
    'delete': 'हटवा',
    'view': 'पहा',
    'save': 'जतन करा',
    'cancel': 'रद्द करा',
    'logout': 'लॉग आउट'
  },
  ml: {
    'dashboard': 'ഡാഷ്‌ബോർഡ്',
    'properties': 'പ്രോപ്പർട്ടികൾ',
    'agents': 'ഏജൻറുകൾ',
    'customers': 'ഉപഭോക്താക്കൾ',
    'transactions': 'ഇടപാടുകൾ',
    'support': 'പിന്തുണ',
    'analytics': 'വിശകലനം',
    'orders': 'ഓർഡറുകൾ',
    'inbox': 'ഇൻബോക്സ്',
    'calendar': 'കലണ്ടർ',
    'users': 'ഉപയോക്താക്കൾ',
    'settings': 'ക്രമീകരണങ്ങൾ',
    'add': 'ചേർക്കുക',
    'search': 'തിരയുക',
    'filter': 'ഫിൽട്ടർ',
    'edit': 'എഡിറ്റ് ചെയ്യുക',
    'delete': 'ഇല്ലാതാക്കുക',
    'view': 'കാണുക',
    'save': 'സേവ് ചെയ്യുക',
    'cancel': 'റദ്ദാക്കുക',
    'logout': 'ലോഗ് ഔട്ട്'
  },
  te: {
    'dashboard': 'డ్యాష్‌బోర్డ్',
    'properties': 'ఆస్తులు',
    'agents': 'ఏజెంట్లు',
    'customers': 'కస్టమర్లు',
    'transactions': 'లావాదేవీలు',
    'support': 'మద్దతు',
    'analytics': 'విశ్లేషణ',
    'orders': 'ఆర్డర్లు',
    'inbox': 'ఇన్‌బాక్స్',
    'calendar': 'క్యాలెండర్',
    'users': 'వినియోగదారులు',
    'settings': 'సెట్టింగ్‌లు',
    'add': 'జోడించు',
    'search': 'శోధించు',
    'filter': 'ఫిల్టర్',
    'edit': 'సవరించు',
    'delete': 'తొలగించు',
    'view': 'చూడు',
    'save': 'సేవ్',
    'cancel': 'రద్దు చేయి',
    'logout': 'లాగ్ అవుట్'
  },
  or: {
    'dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'properties': 'ସମ୍ପତ୍ତି',
    'agents': 'ଏଜେଣ୍ଟ',
    'customers': 'ଗ୍ରାହକ',
    'transactions': 'କାରବାର',
    'support': 'ସମର୍ଥନ',
    'analytics': 'ବିଶ୍ଳେଷଣ',
    'orders': 'ଅର୍ଡର୍',
    'inbox': 'ଇନ୍ବକ୍ସ',
    'calendar': 'କ୍ୟାଲେଣ୍ଡର',
    'users': 'ବ୍ୟବହାରକାରୀ',
    'settings': 'ସେଟିଂ',
    'add': 'ଯୋଡନ୍ତୁ',
    'search': 'ଖୋଜ',
    'filter': 'ଫିଲ୍ଟର',
    'edit': 'ସମ୍ପାଦନ',
    'delete': 'ବିଲୋପ',
    'view': 'ଦେଖ',
    'save': 'ସେଭ୍',
    'cancel': 'ରଦ୍ଦ',
    'logout': 'ଲଗ୍ ଆଉଟ୍'
  },
  as: {
    'dashboard': 'ড্যাশবৰ্ড',
    'properties': 'সম্পত্তি',
    'agents': 'এজেন্ট',
    'customers': 'গ্ৰাহক',
    'transactions': 'কাৰ্যসমূহ',
    'support': 'সমৰ্থন',
    'analytics': 'বিশ্লেষণ',
    'orders': 'অৰ্ডাৰ',
    'inbox': 'ইনবক্স',
    'calendar': 'কেলেণ্ডাৰ',
    'users': 'ব্যৱহাৰকাৰী',
    'settings': 'ছেটিংছ',
    'add': 'যোগ কৰক',
    'search': 'সন্ধান',
    'filter': 'ফিল্টাৰ',
    'edit': 'সম্পাদনা',
    'delete': 'মচক',
    'view': 'চাওক',
    'save': 'ছেভ',
    'cancel': 'বাতিল',
    'logout': 'লগ আউট'
  },
  pa: {
    'dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'properties': 'ਸੰਪੱਤੀਆਂ',
    'agents': 'ਏਜੰਟ',
    'customers': 'ਗ੍ਰਾਹਕ',
    'transactions': 'ਲੈਣ-ਦੇਣ',
    'support': 'ਸਹਾਇਤਾ',
    'analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
    'orders': 'ਆਰਡਰ',
    'inbox': 'ਇਨਬਾਕਸ',
    'calendar': 'ਕੈਲੰਡਰ',
    'users': 'ਯੂਜ਼ਰ',
    'settings': 'ਸੈਟਿੰਗਾਂ',
    'add': 'ਸ਼ਾਮਲ ਕਰੋ',
    'search': 'ਖੋਜ',
    'filter': 'ਫਿਲਟਰ',
    'edit': 'ਸੋਧ',
    'delete': 'ਮਿਟਾਓ',
    'view': 'ਦੇਖੋ',
    'save': 'ਸੰਭਾਲੋ',
    'cancel': 'ਰੱਦ ਕਰੋ',
    'logout': 'ਲਾੱਗ ਆਉਟ'
  },
  gu: {
    'dashboard': 'ડેશબોર્ડ',
    'properties': 'મિલકત',
    'agents': 'એજન્ટ',
    'customers': 'ગ્રાહકો',
    'transactions': 'વ્યવહારો',
    'support': 'સહાય',
    'analytics': 'વિશ્લેષણ',
    'orders': 'ઓર્ડર',
    'inbox': 'ઇનબોક્સ',
    'calendar': 'કેલેન્ડર',
    'users': 'વપરાશકર્તાઓ',
    'settings': 'સેટિંગ્સ',
    'add': 'ઉમેરો',
    'search': 'શોધો',
    'filter': 'ફિલ્ટર',
    'edit': 'સંપાદિત કરો',
    'delete': 'કાઢી નાખો',
    'view': 'જુઓ',
    'save': 'સાચવો',
    'cancel': 'રદ કરો',
    'logout': 'લૉગ આઉટ'
  }
}

